### ISSUE TITLE
Embedding

### ISSUE THREAD

**Issue by michalmuskala** [michalmuskala/mongodb_ecto#11]
We should think about how embedding will work.

I think there are two cases to consider: embedding a full-fledged model, and having a field that would be basically a map without any imposed structure.
With both cases (models/maps) we should support embedding one object or an array of them.

For the unstructured case I think it's a matter of providing a new Ecto type to express this.

For embedded models I imagine the high level interface to be `embeds_one` and `embeds_many` in the schema definition similar to `has_one` and `has_many`.

What are your thoughts?

**Comment by josevalim** [comment]
Yes, that's the correct path. I was thinking about a map field, that is jsonb in postgres, and a map in mongo. Thoughts? /cc @ericmj

**Comment by ericmj** [comment]
:+1: on everything said.

**Comment by josevalim** [comment]
Can we use something for MySQL here?

**Comment by josevalim** [comment]
What about MSSQL? /cc @mobileoverlord

**Comment by mobileoverlord** [comment]
MSSQL doesn't really have anything like this as far as I know. I think their XML data type is as close as it gets. Which I guess is do able in the adapter.

**Comment by mgwidmann** [comment]
If you've ever used Mongoid, it has quite a bit of embedded functionality. In addition to `embeds_one`, `embeds_many` which work both work polymorphic (may be for another day), it also offers a `recursively_embeds_one` as well as a `recursively_embeds_many `.

I've used mongo from several different platforms and I have to say that the biggest piece which stood out was the support for partial updates/deletes/creates of embedded documents (nested at any level) which can only be supported through embedded documents having their own ObjectIds so that they may be targeted in the query. 

From looking at the current ID generation using a GenServer, I have to say that this will become a bottleneck if there are several large records to insert in parallel with all of them waiting on the ID server to return IDs for embedded objects. 

Since IDs are generated entirely client side, theres no reason why the ID shouldn't already exist when you create the Ecto struct like `%User{}`. Additionally, I believe it is important to move away from a GenServer and into a pure function to remove the bottleneck. Mongo's ID generation scheme seems more targeted at non-functional platforms as it requires keeping state of the counter. But this number just needs to be unique and can easily be replaced with a number based on the `:os.timestamp`'s microseconds.

**Comment by josevalim** [comment]
Thanks for the feedback @mgwidmann.

Regarding the bottle neck, we can also spawn one GenServer ID per scheduler and increment the counter per schedule number. So if you have 4 schedulers, one goes 0, 4, 8, 12, the other goes 1, 5, etc. This way we remove any bottleneck. We could also access them on a round robin fashion with an ets table using update counter for the rotation.

**Comment by ericmj** [comment]
@mgwidmann What code were you looking it? The genserver is only used to reset counters, incrementing the counter and generating objids is done in the caller process.

**Comment by mgwidmann** [comment]
@ericmj my mistake, you are correct. Please excuse my comment about the bottleneck. 

However, do keep in mind that tagging every embedded document is a crucial piece of this functionality. Mongoid supports updates in embedded objects by passing in JSON like this for example:

```javascript
{
  "post": {
    ...
    "comments": [
      {"id": "<<OBJECT ID HERE>>", "body": "asdf"}, # This is an update to a prexisting comment
      {"body": "foo bar"}, # Without an ID, this means this is an insert into this array
      {"id": "<<OBJECT ID HERE>>", "_destroy": true} # The _destroy: true flag means this nested record is to be removed from the array
      # This prevents having to squash the whole array structure by doing comments= [...] which will result in lost data when updating concurrently
  ]
}
```

Consider the following snippet as an example:
```ruby
class Post
  include Mongoid::Document
  embeds_many :comments
  accepts_nested_attributes_for :comments, allow_destroy: true
end
class Comment
  include Mongoid::Document
  embedded_in :post
  field :body, type: String
end

p = Post.create(comments: [{body: "foo"}, {body: "asdf"}])
# MOPED: 127.0.0.1:27017 INSERT       database=myapp_development collection=posts documents=[{"_id"=>BSON::ObjectId('5589d5884d61745374000000'), "comments"=>[{"_id"=>BSON::ObjectId('5589d5884d61745374010000'), "body"=>"foo"}, {"_id"=>BSON::ObjectId('5589d5884d61745374020000'), "body"=>"asdf"}]}] flags=[]

p.update(comments: [{id: '5589d5884d61745374010000', body: "bar"}]) # Update one embedded
#   MOPED: 127.0.0.1:27017 UPDATE       database=myapp_ng_development collection=posts selector={"_id"=>BSON::ObjectId('5589d5884d61745374000000')} update={"$set"=>{"comments"=>[{"_id"=>BSON::ObjectId('5589d5884d61745374010000'), "body"=>"bar"}]}} flags=[]

p.update(comments: [{body: "add a new one"}])
#   MOPED: 127.0.0.1:27017 UPDATE       database=myapp_ng_development collection=posts selector={"_id"=>BSON::ObjectId('5589d5884d61745374000000')} update={"$set"=>{"comments"=>[{"_id"=>BSON::ObjectId('5589d63c4d61745374060000'), "body"=>"add a new one"}]}} flags=[]

p.update(comments: [{id: '5589d63c4d61745374060000', body: 'update this one'}, {body: 'while adding this one'}])
#   MOPED: 127.0.0.1:27017 UPDATE       database=weddingwire_ng_development collection=posts selector={"_id"=>BSON::ObjectId('5589d5884d61745374000000')} update={"$set"=>{"comments"=>[{"_id"=>BSON::ObjectId('5589d63c4d61745374060000'), "body"=>"update this one"}, {"_id"=>BSON::ObjectId('5589d6a44d61745374080000'), "body"=>"while adding this one"}]}} flags=[]

```

Some food for thought...

**Comment by michalmuskala** [comment]
@mgwidmann thank you, that seems interesting.

How do you replace an entire embedded collection. Do you use `p.comments = [...]` in that case?
And do this partial updates work on more nested embeddings?

**Comment by josevalim** [comment]
@mgwidmann @michalmuskala it is worth pointing out that we already calculate only the fields that have changed in Ecto with changesets. So if all we need to support this feature on the adapter side is to generate ids for the embeds, we should definitely do it.

**Comment by mgwidmann** [comment]
@michalmuskala Setting an empty array like `p.update(comments: [])`, will clear the collection. 
```
  MOPED: 127.0.0.1:27017 UPDATE       database=myapp_ng_development collection=posts selector={"_id"=>BSON::ObjectId('5589d5884d61745374000000')} update={"$pullAll"=>{"comments"=>[{"_id"=>BSON::ObjectId('558aba994d617453740b0000'), "body"=>"foo"}]}} flags=[]
  MOPED: 127.0.0.1:27017 UPDATE       database=myapp_ng_development collection=posts selector={"_id"=>BSON::ObjectId('5589d5884d61745374000000')} update={"$unset"=>{"comments"=>true}} flags=[]
```
As you can see, its possible to have a single save run multiple statements. This is typical for mongo as not everything can be done in a single statement.

Via ruby code this can also be done with something like `p.comments.clear` which does:
```
  MOPED: 127.0.0.1:27017 UPDATE       database=myapp_ng_development collection=posts selector={"_id"=>BSON::ObjectId('5589d5884d61745374000000')} update={"$unset"=>{"comments"=>true}} flags=[]
```
From testing, if you do `p.comments = []` mongoid does the following (without calling save actually):
```
  MOPED: 127.0.0.1:27017 UPDATE       database=myapp_ng_development collection=posts selector={"_id"=>BSON::ObjectId('5589d5884d61745374000000')} update={"$pullAll"=>{"comments"=>[{"_id"=>BSON::ObjectId('558ab95c4d61745374090000'), "body"=>"one"}, {"_id"=>BSON::ObjectId('558ab95c4d617453740a0000'), "body"=>"two"}]}} flags=[]
```

This is just sugar for a lot of the same functionality which is more useful in an OO architecture. 

I've worked with Mongoid for the last 3 years, even patched the codebase one time. Now I primarily use ActiveRecord (so I'm less familiar with some of the more recent updates to Mongoid or Mongo) so if you have any questions feel free to call me out and I'll do my best to answer them.

@josevalim If thats true in a nested fashion (including embedded documents), then the only thing thats needed is transform that changeset into the appropriate query/queries like you see above.

**Comment by scottmessinger** [comment]
Hi! I'm a Mongoid user and the code examples have a couple mistakes in them:

1) This one was correct -- this will create a post with two comments.

```ruby
p = Post.create(comments: [{body: "foo"}, {body: "asdf"}])
# MOPED: 127.0.0.1:27017 INSERT       database=myapp_development collection=posts documents=[{"_id"=>BSON::ObjectId('5589d5884d61745374000000'), "comments"=>[{"_id"=>BSON::ObjectId('5589d5884d61745374010000'), "body"=>"foo"}, {"_id"=>BSON::ObjectId('5589d5884d61745374020000'), "body"=>"asdf"}]}] flags=[]
```


2) This example (and the following examples) aren't correct. The ruby (or the resulting mongo query) will not update one comment -- it wipes out the comments array and replaces it with an array of one comment.

```ruby
p.update(comments: [{id: '5589d5884d61745374010000', body: "bar"}]) # Update one embedded
#   MOPED: 127.0.0.1:27017 UPDATE       database=myapp_development collection=posts selector={"_id"=>BSON::ObjectId('5589d5884d61745374000000')} update={"$set"=>{"comments"=>[{"_id"=>BSON::ObjectId('5589d5884d61745374010000'), "body"=>"bar"}]}} flags=[]
```


3) Ditto. The comments array is replaced with one comment without an id.
```ruby
p.update(comments: [{body: "add a new one"}])
#   MOPED: 127.0.0.1:27017 UPDATE       database=myapp_development collection=posts selector={"_id"=>BSON::ObjectId('5589d5884d61745374000000')} update={"$set"=>{"comments"=>[{"_id"=>BSON::ObjectId('5589d63c4d61745374060000'), "body"=>"add a new one"}]}} flags=[]
```


---

4) Ditto. The comments array is wiped out and replaced with two comments.

```ruby
p.update(comments: [{id: '5589d63c4d61745374060000', body: 'update this one'}, {body: 'while adding this one'}])
#   MOPED: 127.0.0.1:27017 UPDATE       database=myapp_development collection=posts selector={"_id"=>BSON::ObjectId('5589d5884d61745374000000')} update={"$set"=>{"comments"=>[{"_id"=>BSON::ObjectId('5589d63c4d61745374060000'), "body"=>"update this one"}, {"_id"=>BSON::ObjectId('5589d6a44d61745374080000'), "body"=>"while adding this one"}]}} flags=[]
```

---

To update an embedded document in Mongo, you have to use the positional operator (`$`). E.g. 

```ruby
$db.find({"comments._id": BSON::ObjectId("5589d63c4d61745374060000")}).update({"$set" => {"comments.$.body": "A new update"}})
```

One of the historical problems with Mongoid and Mongo is the positional operator can't be nested. Take this 5 year old issue filed by the creator of Mongoid: https://jira.mongodb.org/browse/SERVER-831. This means that an embedded document can't have another embedded document (and be updated atomically). When the top level embedded document is updated, it has to include all the embedded documents within it. For an example of this problem, check out: http://artsy.github.io/blog/2013/02/09/data-corruption-and-concurrent-updates-to-embedded-objects-with-mongoid/

After working with Mongo for 4 years and working on real time web applications for the last 2, I think embedded documents should be stored as a map (instead of an array). When embedded docs are stored in the array, we need the positional operator to find the right document or we use the position (e.g. `comments.0.body`). While the positional operator is nifty, it's not a common construct in other languages or frameworks. It's also limited as the positional operator can only access one embedded document per query. When multiple queries are needed to update a document, one of the significant advantages of Mongo is taken away -- the ability to store a structured document and then make atomic updates to it. If we don't use the positional operator, we can use the index notation (e.g. `comments.0.body`) but this is awful for collaborative editing as it makes it difficult to commute changes to a document as the position of the elements in an array isn't guaranteed to stay constant.

If embedded documents were stored as a map, these problems go away. If I were designing a new adapter for Mongo, I'd store all embedded documents as maps with ObjectIds as the keys. This way, there wouldn't be any limitations on nesting embedded documents.

For users who are bringing an existing database to their Elixir project, I'd encourage them to use the MongoDB update operators (e.g. `$set`, `$addToSet`, `$push`, etc) exposed through the driver/ecto. 

Hopefully that's helpful! More than happy to talk more or brainstorm ideas.

**Comment by mgwidmann** [comment]
@scottmessinger Yes, you are correct in that case, sorry. I meant to use `comments_attributes` and then it will do like I mentioned. See below:

```ruby
# Needs this added to the class
class Post
  accepts_nested_attributes_for :comments, allow_destroy: true
end

p.update(comments_attributes: [{id: '558ae89c4d6174654d010000', body: 'bar'}, {body: 'new comment'}])
#   MOPED: 127.0.0.1:27017 UPDATE       database=weddingwire_ng_development collection=posts selector={"_id"=>BSON::ObjectId('558ae89c4d6174654d000000')} update={"$set"=>{"body"=>"bar"}, "$pushAll"=>{"comments"=>[{"_id"=>BSON::ObjectId('558ae8d94d6174654d030000'), "body"=>"new comment"}]}} flags=[]

p.comments.map(&:body)
# ["bar", "asdf", "new comment"]
```

**Comment by mgwidmann** [comment]
@scottmessinger Thats an interesting idea. I'm aware of the problem you are talking about. Storing embeds_many in an `{}` rather than `[]` would solve the problem you are talking about except that it destroys ordering, which in many cases can be important. You'd have to find a way to preserve order. I assume when serialized it would then create a list in Elixir? 

Additionally, I don't think the `ObjectId("...")` type can be a key, so it will need to be the string variant. 

Also, your idea eliminates the problem with indexing a doubly nested array, so :+1: for that.

**Comment by scottmessinger** [comment]
@mgwidmann Thanks for clearing that up! I figured there was a way in MongoId. I use embedded documents, but I update them via the driver (it's a long story).

Regarding ObjectId as keys, you're totally right -- it would have to the string form.

Regarding ordering, that's a great point. In my app, I give each embedded document a `position` field that increments by 1000. This way, changes to the order affect as few documents as possible. E.g.:
```js
// Before
{id: 1, position: 1000}
{id: 2, position: 2000}
{id: 3, position: 3000}

// <-- Swap the 2nd and third elements -->

// After
{id: 1, position: 1000}
{id: 3, position: 1500}
{id: 2, position: 2000}
```

Of course, sometimes the position fields would need to be redrawn if the position can't be changed without causing a conflict. It's a pretty easy operation, so it's not too bad.

**Comment by johnnyshields** [comment]
Why was this issue closed? I have a Rails Mongoid app which uses many embedded objects, and it will be difficult to migrate to Elixir without support for this.

@scottmessinger regarding using array vs. map, I believe array has advantages if you make an index on the embeded objects. Array will also be needed to support migration from the many Mongoid apps already in existence. Ideally users could be given a choice of the two patterns (array or map).

**Comment by michalmuskala** [comment]
The issue was closed since the support for embedded schemas was added to ecto itself.

**Comment by johnnyshields** [comment]
And it works seamlessly with Mongo Ecto?

**Comment by michalmuskala** [comment]
Yes
