### ISSUE TITLE
(FunctionClauseError) no function clause matching in Ecto.Schema.do_load/4

### ISSUE THREAD

**Issue by Slavenin** [michalmuskala/mongodb_ecto#110]
Hi!
I create in my collection unique index, after that insert raise error:
```
** (FunctionClauseError) no function clause matching in Ecto.Schema.do_load/4
    (ecto) lib/ecto/schema.ex:1171: Ecto.Schema.do_load(%Crawler.MongoLinks{__meta__: #Ecto.Schema.Metadata<:built, "links">, id: nil, link: nil}, %{id: :binary_id, link: :string}, {false, {:unique, "link"}}, #Function<21.13591161/2 in Ecto.Repo.Schema.postprocess/5>)
    (ecto) lib/ecto/schema.ex:1161: Ecto.Schema.__load__/6
```
My Schema:
```elixir
defmodule Crawler.MongoLinks do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "links" do
      field :link, :string
  end

  def changeset(link, params \\ %{}) do
      link
          |> cast(params, [:link])
          |> validate_required([:link])
#          |> unique_constraint(:link)
  end
end
```

**Comment by michalmuskala** [comment]
What ecto version are you using? What mongodb_ecto version? What mongodb version?

Could you also show the code that actually triggers the error?

**Comment by Slavenin** [comment]
`:ecto, "2.0.6", "9dcbf819c2a77f67a66b83739b7fcc00b71aaf6c100016db4f798930fa4cfd47"`
`"mongodb_ecto": {:git, "https://github.com/michalmuskala/mongodb_ecto", "95f70999ddfbd0bc54958799cf0d4a9aa93b2b82", [branch: "ecto-2"]}`
`"mongodb": {:git, "https://github.com/ericmj/mongodb.git", "af98466040e368f4e7bd7da4f29f52641ddf30ac", [branch: "master"]},`

```elixir
def handle_cast({:put, links}, state) do
    Crawler.MongoRepo.insert_all(
	Crawler.MongoLinks, (for link <- links, do: %{link: link})
    )
    {:noreply, state}
end
```

**Comment by ankhers** [comment]
It looks like it is failing because of the unique constraint. Specifically, it looks like one of your links has the value of `nil` (which, unlike SQL, Mongo will raise an error on for unique indexes) which is already stored in Mongo. Using `insert_all/3` does not take advantage of your `changeset/2` functions. It is meant to be a low level "just put data in my database" kind of tool.

Unfortunately, if you want to handle duplicate data gracefully, you are probably going to want to do something along the lines of this

```elixir
def handle_cast({:put, links}, state) do
  for link <- links do
    %Crawler.MongoLinks{}
    |> Crawler.MongoLinks.changeset(%{link: link})
    |> Crawler.MongoRepo.insert()
  end
end
```

This is unfortunate as it will call the database N times where N is the number of links you are trying to insert. The real problem is that Mongo doesn't really support transactions, so this adapter does not support `Repo.transaction` which means you cannot use `Ecto.Multi`.

With that being said, it may be possible to put something in place (again, even though Mongo doesn't truly support transactions) that would allow a limited use of `Ecto.Multi`. But that would need to be looked into.

**Comment by Slavenin** [comment]
Tnx! You code is work! But why my version did not work?
```elixir
defmodule Crawler.MongoLinks do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "links" do
      field :link, :string
  end

  def changeset(link, params \\ %{}) do
      link
          |> cast(params, [:link])
          |> validate_required([:link])
          |> validate_format(:link, ~r/\/[^\/]+/)
          |> validate_length(:link, min: 1)
          |> unique_constraint(:link)
  end
end
```
```elixir
recs =
    Enum.uniq(links)
    |> Enum.filter(fn (link) ->
        Crawler.MongoLinks.changeset(%Crawler.Links{}, %{link: link}).valid?
    end)
    |> Enum.map(fn link -> %{link: link}  end)

Crawler.MongoRepo.insert_all(Crawler.MongoLinks, recs)
```

**Comment by ankhers** [comment]
Are you absolutely positive that is the query that is being run? When I run a very similar query, I get a different logged result.

```
Repo.one(from u in MyApp.User, where: u.email == ^"my@email.com", select: count("*"))
[debug] QUERY OK db=11.8ms
COMMAND [count: "users", query: %{email: "my@email.com"}] []
1
```

If you run that exact query in `iex`, what do you see?

**Comment by Slavenin** [comment]
This is my error. I am write `Crawler.Repo.one(q) > 0` instead of ` Crawler.MongoRepo.one(q) > 0`
Tnx!
